name: dart_openapi_generator
description: A Dart tool for generating models and schemas from OpenAPI JSON specifications
version: 1.0.0
homepage: https://github.com/yourusername/dart_openapi_generator

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  args: ^2.4.2
  http: ^1.1.0
  json_annotation: ^4.8.1
  path: ^1.8.3
  recase: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^3.0.0

executables:
  dart_openapi_generator: